name: ci
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.1']
        magento: ['2.4.4', '2.4.5']
        coveralls: [ false ]
        include:
          - php-versions: '8.1'
            magento: '2.4.6'
            operating-system: 'ubuntu-latest'
            coveralls: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          coverage: xdebug
          extensions: bcmath, gd

      - name: Install Composer dependencies
        run: composer install

      - name: Install Magento 2.4.4
        if: matrix.magento == '2.4.4'
        run: composer update --with-dependencies magento/framework:103.0.4 laminas/laminas-code:4.5.1 symfony/yaml symfony/console madewithlove/license-checker

      - name: Install Magento 2.4.5
        if: matrix.magento == '2.4.5'
        run: composer update --with-dependencies magento/framework:103.0.5 laminas/laminas-code:4.5.2 roave/security-advisories symfony/yaml symfony/console madewithlove/license-checker

      - name: Install Magento 2.4.6
        if: matrix.magento == '2.4.6'
        run: composer update --with-dependencies magento/framework:103.0.6 laminas/laminas-code:4.10.0 roave/security-advisories symfony/yaml symfony/console madewithlove/license-checker

      - name: Composer license check
        run: composer check-license

      - name: Codesniffer
        run: composer cs-check

      - name: Neon linting
        run: |
          ./bin/ci_neon_lint
          ./bin/ci_markdown_neon_lint

      - name: Static code analysis
        if: (matrix.magento != '2.4.0' && matrix.magento != '2.4.1')
        run: composer analyze

      - name: Unittests
        if: matrix.coveralls == false
        run: composer test

      - name: Unittests with coverage
        if: matrix.coveralls == true
        run: composer coverage

      - name: Coveralls report
        if: matrix.coveralls == true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer require php-coveralls/php-coveralls
          ./vendor/bin/php-coveralls --coverage_clover=clover.xml -v
